// <auto-generated />
namespace Expense_Overview.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Renametosingular : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renametosingular));
        
        string IMigrationMetadata.Id
        {
            get { return "202211201241241_Rename to singular"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
